language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script: make test-coverage
after_success: make test-coveralls
before_script: flake8
notifications:
  email: false
